os: linux
dist: bionic

language: c

# If travis-ci starts offering something newer than ubuntu 18, it will contain
# the correct gcc and binutils, and we can skip the upgrade done here.
#
# Both current Debian Stable and Ubuntu LTS have these packages...
#

install:
    - sudo sed -i -e 's/bionic/eoan/g' /etc/apt/sources.list
    - sudo apt-get update
    - sudo make build-dep

script:
    - make all
